### ISSUE TITLE
Is there any documentation for IntegerKeys?

### ISSUE THREAD

**Issue by bm3racer** [fallenidol/AspNet.Identity.IntegerKeys#1]
I just signed up to GitHub in order to contact you (FallenIdol) as I am from Melbourne Australia, I couldn't find a way to message you directly so I am creating this Issue Ticket.

Is there any documentation on how to use IntegerKeys? I have searched the internet for hours following every lead I could, there is nothing. Not even a blog post about someone using it or showing an example of use.

Right now I have an ASP.NET MVC Project just started, with IntegerKeys added via nuget & all other nuget packages updated. I had a look inside the AspNet.Identity.IntegerKeys namespace in order to see if I could figure it out that way, but I got stuck literally on every item, since there are no UI hints re what to send for which arguments or what to expect in return. I don't even have the slightest idea on how to proceed, and given not being able to find any documentation - I am at a dead end.

Is there a link you could provide or information you could share with us so that we can make good use of your valuable tool? For me, beginning a database without IntegerKeys (and using GUID's) is just not an option, given the number of columns & tables I will create. The space taken by the GUID's would be an absolute waste and I'd rather start with Integer's from the beginning rather than trying to convert an application from GUID's to Integer's in the future. Such an attempt would be an error prone nightmare.

Thank you for reading this Issue, may the crispy Melbourne climate find you in Brisbane & relieve you of the beautiful yet stuffy weather :).

Eran

**Comment by fallenidol** [comment]
HI Eran, Thank you for getting in contact. If you can wait a bit longer I will work on an example project and add it to this repository in the next few days. I will send you a message when it is added.

**Comment by bm3racer** [comment]
Hello Paul,

Thank you very much for your response. I have no issue re waiting for the sample, whenever you have the time & it is convenient for you would be more than fantastic (no need to rush).

Although I code in VB.NET out of preference, I can fluently read (and write) in C#. After you've made the sample, I will implement it in VB.NET (using MVC) and can upload or provide a VB version for you or your audience if this is of value to anyone. Additionally, it might just be useful as a second sample.

Thanks again & looking forward to using your DLL.

Eran

**Comment by fallenidol** [comment]
I've now added an example asp.net mvc project which you can refer to.
